name: Revive CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Use a service for the database if needed (e.g., PostgreSQL)
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run backend tests
      run: |
        cd backend
        python -m unittest discover

    # Set up Node.js environment (if needed for frontend tests)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Run frontend tests
      run: |
        cd frontend
        npm test

    # Run Selenium tests
    - name: Run Selenium tests
      run: |
        cd tests  # Assuming your Selenium tests are in the 'tests' directory
        python run_selenium_tests.py
